include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style and Best Practices
    - prefer_final_fields
    - prefer_final_locals 
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - prefer_expression_function_bodies
    - always_put_required_named_parameters_first
    - use_key_in_widget_constructors
    - unnecessary_this
    - always_use_package_imports
    - depend_on_referenced_packages
    - annotate_overrides
    - avoid_init_to_null
    - avoid_unnecessary_containers
    - avoid_redundant_argument_values
    - avoid_returning_null
    - avoid_types_on_closure_parameters
    - use_setters_to_change_properties
    - prefer_typing_uninitialized_variables
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - type_annotate_public_apis
    - unnecessary_late

    # Flutter-specific
    - prefer_const_constructors_in_immutables
    - use_rethrow_when_possible

    # BLoC/Cubit Recommended
    - avoid_print                            
    - avoid_dynamic_calls                    
    - avoid_positional_boolean_parameters    
    - avoid_void_async                       
    - prefer_final_in_for_each               

