name: yummify
description: "A modern and intuitive restaurant app with Firebase authentication, menu browsing, and cart management functionality."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Debugging
  # device_preview: ^1.2.0
  # flutter_native_splash: ^2.4.6

  # Controller
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.5
  hydrated_bloc: ^10.1.1

  # Core
  intl: ^0.19.0
  get_it: ^8.0.3
  url_launcher: ^6.3.2
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3


  # UI
  shimmer: ^3.0.0
  fluttertoast: ^8.2.12
  cupertino_icons: ^1.0.8

  # Database
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.7
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/
    - images/contact/
    - images/onboarding/

flutter_assets:
  classname: AssetsManager
  filename: assets_manager.dart
  output_path: lib/core/constants/
  assets_path:
    - images/
    - images/contact/
    - images/onboarding/

flutter_intl:
  enabled: true
  arb_dir: lib/core/localization/l10n
  output_dir: lib/core/localization/generated
